local SCMODS_ITEMS =
{
	ABILITIES =
	{
		CLOAK_COOLDOWN = "Cloak Recharging: {1} {1:TURN|TURNS}",
		CLOAK_DESC = "Lasts {1} {1:TURN|TURNS}. Requires cooldown to use again.",
		CLOAK_DURATION = "Cloak Active: {1} {1:TURN|TURNS}",
		EMP_CONC_PRIME = "Prime Concussive EMP",
		EMP_CONC_PRIME_DESC = "Place the Concussive EMP Pack on the ground and prime it. Detonate it using the mainframe.",
		EMP_CONC_USE = "Detonate Concussive EMP",
		EMP_CONC_USE_DESC = "KO guards and disable devices in a 6 tile radius for 2 turns.",
		HUNT = "HUNT",
		HUNT_DESC = "Destroys DAEMON program on %s",
		VELOCITY_DESC = "Hack this console to reclaim its PWR and boost AP.",
		VELOCITY_TIP = "BOOST [{1} PWR] for {2} AP",
		VELOCITY_TIP_BONUS = "BOOST [{1} PWR] +{2} BONUS for {3} AP",
		VENTRICULAR_DESC_1 = "Refresh attacks and gain +1 PIERCING for 1 turn.",
		VENTRICULAR_DESC_2 = "Gain an attack and +%d PIERCING for 1 turn.",
		VENTRICULAR_DESC_3 = "Gain unlimited attacks and +2 PIERCING for 1 turn.",
	},
	FLY_TXT =
	{
		ATKREF = "ATTACKS REFRESHED",
		ATKUP = "+1 ATTACK",
		CLOAKED = "CLOAKED\n{1} {1:TURN|TURNS}",
		CLOAKED_NODURATION = "CLOAKED",
		PIERCEUP = "+%d PIERCING",
		VELOCITY = "+{1} AP BOOST",
	},
	GENOPTIONS =
	{
		EDITEDITEMS = "Enable Edited Items",
		EDITEDITEMS_TIP = "Overwrites the data for existing items, including those from the Contingency Plan DLC. This is done to prevent the unchanged DLC items showing up in shops and such.\nMay conflict with other item mods.\n<c:FF8411>CHANGES</c>\nVentricular Lance I\nPrototype Chip\nBiogenic D.A.R.T.\nThermal Disruptor III, IV, and other tier IV Disruptors.",
		MONST3RSALES = "Enable Edited Monst3r-Sales",
		MONST3RSALES_TIP = "Change Monst3r's offers between missions to trim some garbage items and add a few more useful ones.",
		NEWITEMS = "Enable New Items",
		NEWITEMS_TIP = "<c:FF8411>ITEMS</c>\nCombat Stimulator\nPiercing Biogenic D.A.R.T.\nVentricular Lance II, III, IV\nPortable Router\nCloaking Bubble\nVelocity/Hunter/Econ 2 Chips\nConcussive EMP",
	},
	ITEMS =
	{
		CLOAK_BUBBLE = "Cloaking Bubble",
		CLOAK_BUBBLE_TOOLTIP = "Renders the user and nearby agents invisible for 4 turns, unless they move or attack. Fails to cloak agents targeted by enemies.",
		CLOAK_BUBBLE_FLAVOR = "This rig's stationary images exact fewer resources than normal, affecting a wider area for longer. Perfect for when multiple people need a place to hide, but don't bust the bubble.",
		COMBAT_STIMULATOR = "Combat Stimulator",
		COMBAT_STIMULATOR_TOOLTIP = "Gain 3 AP after any ATTACK.",
		COMBAT_STIMULATOR_FLAVOR = "Amplifies the host's natural fight-or-flight response.",
		DART_GUN_BIOPIERCE = "Piercing Biogenic D.A.R.T.",
		DART_GUN_BIOPIERCE_FLAVOR = "In addition to regenerating toxin projectiles, this weapon's bioreactor produces a corrosive slime that burns through armor.",
		ECON_CHIP_2 = "Econ Chip II",
		ECON_CHIP_2_TOOLTIP = "An overclocked Econ Chip. Collects credits from consoles instead of PWR. 50 credits per PWR point.",
		EMP_CONCUSSIVE = "Concussive EMP Pack",
		EMP_CONCUSSIVE_TOOLTIP = "Place on the ground. Detonate it using the mainframe. KO all guards and disable all mainframe devices and drones in a range of 6 tiles.",
		EMP_CONCUSSIVE_FLAVOR = "A micro-nuclear device that generates both a kinetic shockwave and EMP. Usually installed as self-destruct mechanisms on military drones and stationary defenses.",
		HUNTER_CHIP = "Hunter Chip",
		HUNTER_CHIP_TOOLTIP = "Kills a hidden or revealed Daemon on a mainframe device.",
		HUNTER_CHIP_FLAVOR = "This modern deletion tool was developed as a last-resort safety mechanism for unshackled A.I. It is entirely hardware based, unhackable and unstoppable.",
		PORTABLE_ROUTER = "Portable Router",
		PORTABLE_ROUTER_TOOLTIP = "Breaks 1 random firewall per turn when deployed. Cannot reduce firewalls below 1. Deploying has a 2 turn cooldown.",
		PORTABLE_ROUTER_FLAVOR = "A Portable Router grants Incognita limited direct access to the local mainframe.",
		VELOCITYDRIVE = "Velocity Chip",
		VELOCITYDRIVE_TOOLTIP = "Use at a console to boost AP by double the amount of PWR reclaimed.",
		VELOCITYDRIVE_FLAVOR = "In addition to console optimization, this chip boosts excess power to calculate the most efficient route through the facility.",
		VENTRICULAR_LANCE_1 = "Ventricular Lance I",
		VENTRICULAR_LANCE_1_TOOLTIP = "Refreshes the agent's attacks and gives +1 ARMOR PIERCING to all weapons for one turn.",
		VENTRICULAR_LANCE_2 = "Ventricular Lance II",
		VENTRICULAR_LANCE_2_TOOLTIP = "Gives the agent an extra attack and +1 ARMOR PIERCING to all weapons for one turn.",
		VENTRICULAR_LANCE_3 = "Ventricular Lance III",
		VENTRICULAR_LANCE_3_TOOLTIP = "Gives the agent an extra attack and +2 ARMOR PIERCING to all weapons for one turn.",
		VENTRICULAR_LANCE_4 = "Ventricular Lance IV",
		VENTRICULAR_LANCE_4_TOOLTIP = "Gives the agent unlimited attacks and +2 ARMOR PIERCING to all weapons for one turn.",
	}
}
return SCMODS_ITEMS
